stages:
  split:
    cmd: python src/data/split_data.py
    deps:
    - data/raw_data
    - src/data/split_data.py
    outs:
    - data/processed_data
  scale:
    cmd: python src/data/normalize_data.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/normalize_data.py
    outs:
    - data/scaled/X_test_scaled.csv
    - data/scaled/X_train_scaled.csv
  grid:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed_data/y_train.csv
    - data/scaled/X_train_scaled.csv
    - src/models/grid_search.py
    outs:
    - models/best_params.pkl
  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/processed_data/y_train.csv
    - data/scaled/X_train_scaled.csv
    - models/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/trained_model.pkl
  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
    - data/processed_data/y_test.csv
    - data/scaled/X_test_scaled.csv
    - models/trained_model.pkl
    - src/models/evaluate_model.py
    outs:
    - data/prediction/predictions.csv
    metrics:
    - metrics/scores.json:
        cache: false
